---
version: "3"

tasks:
  default: task --list-all

  build:
    deps:
      - clean
    cmds:
      - zensical build --clean

  run:
    aliases: [serve, server]
    deps:
      - build
    cmds:
      - zensical serve

  # chinese:
  #   cmds:
  # - cp ../chinese/obsidian/chinese/Single\ Character/*.md docs/chinese/
  # - cp ../chinese/obsidian/chinese/Multi\ Character/*.md docs/chinese/
  # - ln -s ../chinese/obsidian/chinese/Single\ Character/*.md docs/chinese/single
  # - ln -s ../chinese/obsidian/chinese/Multi\ Character/*.md docs/chinese/multi

  clean:
    cmds:
      - rm -rf ./.cache
      # - rm -rf ./.venv

  fmt: taplo format zensical.toml
