name: Documentation

on:
  release:
    types: [published]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/configure-pages@v6
      - uses: actions/setup-python@v7
        with:
          python-version-file: ".python-version"
      - run: python --version
      - uses: astral-sh/setup-uv@v10
        with:
          version: 0.12.13
      - run: uv --version
      - run: |
          uv venv
          source .venv/bin/activate
          uv sync
          zensical build --clean
      - uses: actions/upload-pages-artifact@v5
        with:
          path: site
      - id: deployment
        uses: actions/deploy-pages@v5
